### ISSUE TITLE
Chessel's variant of the fourth corner statistic

### ISSUE THREAD

**Issue by cblaix** [zdealveindy/weimea#3]
Hello,

I was trying out the fourth.corner.ade function to obtain Chessel's variant of the fourth corner statistic and I seemed to get the Chessel fourth corner statistic when I typed "chessel=F" and I received the normal statistic when I typed "chessel=T". I first got suspicious when I realized that I had a statistic higher than 1 after specifying "chessel=T". When I divided the number with the square root of the highest eigenvalue of the CA on the species dataset I got a value very close to the one given by "chessel=F".

All the best,

Cian

p.s. You should also change the title to specify that the Peres-Neto et al. paper was published in 2017! That is if you are referring to this one: "Linking trait variation to the environment: critical issues with community‐weighted mean correlation resolved by the fourth‐corner approach".

**Comment by zdealveindy** [comment]
Hi Cian,
Thanks for your comment. Could you perhaps offer some reproducible example of this issue? I tried (below) and the function seems to work as intended, but you may have different data in hand which may cause the bug. Definitely, you should not be able to get Chessel fourth corner higher than 1, that makes no sense. Note that this function was built only for the experimental purpose (it's using the fourthcorner function from ade4, and I use it to compare the results with weimea native fourth.corner function).

```
library (weimea)
data (vltava)

t <- vltava$herbs$traits$SLA [!is.na (vltava$herbs$traits$SLA)]
e <- vltava$env$COVERE32
L <- vltava$herbs$spe [, !is.na (vltava$herbs$traits$SLA)]

# standard fourth corner statistic:
fourth.corner.ade (sitspe = L, speatt = t, env = e, fc.test = 6, perm = 199, chessel = F)
#          names fourthcorner P.value
# 1 env / speatt    0.1627155    0.01

# Chessel fourth corner statistic:
fourth.corner.ade (sitspe = L, speatt = t, env = e, fc.test = 6, perm = 199, chessel = T)
#          names fourthcorner P.value
# 1 env / speatt    0.1877419    0.01
```
Thanks! David

BTW, the reference in the title is correct - the fourth corner function in weimea was coded according to the detailed description of fourth corner algorithm in the Appendix to Peres-Neto et al. 2012 paper, not 2017 (but I should double check this once again). But you are right, I should make it more explicit what is actually the reference for.

**Comment by cblaix** [comment]
Hi David,

I should have specified that I used RLQ axes scores instead of actual environmental variables when calculating the fourth corner statistics. Maybe that is what is causing the bug. Here is a reproducible example.

```
 data(aviurba)
   coa1 <- dudi.coa(aviurba$fau, scannf = FALSE, nf = 2)
   dudimil <- dudi.hillsmith(aviurba$mil, scannf = FALSE, nf = 2, row.w = coa1$lw)
   duditrait <- dudi.hillsmith(aviurba$traits, scannf = FALSE, nf = 2, row.w = coa1$cw)
   rlq1 <- rlq(dudimil, coa1, duditrait, scannf = FALSE, nf = 2)
   
fourth<-fourth.corner.ade( aviurba$fau,aviurba$traits, rlq1$lR, fc.test = 6, perm = `nrepet,chessel=T)
```
I was not familiar with that article. I will take a look at it!

**Comment by cblaix** [comment]
I should also have said that I got this error: the condition has length > 1 and only the first element will be used.

I think that the function is working fine and that maybe Chessel's variant should not be applied to calculate the fourth corner statistic when using RLQ axes as variables.

**Comment by zdealveindy** [comment]
Thanks for the example, it helps. I slightly modified it to make it fully reproducible:

```
library (ade4)
data(aviurba)
coa1 <- dudi.coa(aviurba$fau, scannf = FALSE, nf = 2)
dudimil <- dudi.hillsmith(aviurba$mil, scannf = FALSE, nf = 2, row.w = coa1$lw)
duditrait <- dudi.hillsmith(aviurba$traits, scannf = FALSE, nf = 2, row.w = coa1$cw)
rlq1 <- rlq(dudimil, coa1, duditrait, scannf = FALSE, nf = 2)

library (weimea)
nrepet <- 199
fourth<-fourth.corner.ade( aviurba$fau,aviurba$traits, rlq1$lR, fc.test = 6, perm = nrepet, chessel=T)
```
True is that for some of the relationships, the Chessel fourth corner is larger than 1:
```
...
7    AxcR1 / feed..ground   1.10041231   0.895
8    AxcR2 / feed..ground   1.08307004   0.635
...
```
The thing here is that your traits are qualitative variables (aviurba$traits), and you related them to the quantitative environment (here site scores from RLQ). The test statistic for the relationship of quant/qual is not the fourth corner correlation, but ANOVA-like pseudo-F statistic (see Dray & Legendre 2008, chapter Linking one qualitative variable and one quantitative variable). The Chessel form was described by Peres-Neto et al. 2017 for fourth corner **correlation**, relating quantitative traits with a quantitative environment. 
The fourth corner implementation in weimea now is still only for quantitative-quantitative relationship, and the other options need to be added. The thing about Peres-Neto et al. 2017 is that they described the relationship between CWM and SNC approach and fourth corner approach only in the context of quantitative variables, and unless the further theory is developed, it should be applied only to this combination. So, I suggest to drop using Chessel at this moment, or, ask the authors for their suggestion whether there is some Chessel-like analogy for the other fourth corner statistics than correlation (there is also chi square for qual-qual).

**Comment by cblaix** [comment]
Thank you David, that makes sense. I hope that I did not waste too much of your time!

**Comment by zdealveindy** [comment]
Hi Cian,
Not at all, I appreciate your feedback! Good luck with your analysis. I plan to get to remaking weimea library soon, so if any other bug, I will be happy to hear about that so as I can fix it.
Cheers,
David
